# ===========================
# SERVER
# ===========================
server.port=8080

# ===========================
# DATABASE - PostgreSQL
# ===========================
spring.datasource.url=jdbc:postgresql://localhost:5432/loanflow_db
spring.datasource.username=postgres
spring.datasource.password=loanflow123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===========================
# JPA / HIBERNATE
# ===========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===========================
# DATA SQL (seed inicial)
# ===========================
spring.sql.init.mode=never
spring.sql.init.data-locations=classpath:data.sql
spring.jpa.defer-datasource-initialization=true

# ===========================
# JWT
# ===========================
jwt.secret=loanflow_super_secret_key_tecsup_2025_examen_final_stefano
jwt.expiration=86400000

# ===========================
# CORS
# ===========================
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000
